name: eleven_systems
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  objectbox: ^4.0.2
  objectbox_flutter_libs: 4.0.2
  path_provider: ^2.0.5
  logger: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7  
  mocktail: ^1.0.4
  build_runner: ^2.4.12
  objectbox_generator: ^4.0.2
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/contacts.json
